<a href="https://colab.research.google.com/github/subupkrl/Python/blob/master/DS_Day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
file_path = "/content/drive/MyDrive/train.csv"
df = pd.read_csv(file_path)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
#Looping over a column
for name in df['Name'][0:5]:
  print(name.upper())

BRAUND, MR. OWEN HARRIS
CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS THAYER)
HEIKKINEN, MISS. LAINA
FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
ALLEN, MR. WILLIAM HENRY


In [ ]:
for name in df["Name"][7:15]:
  print(name.lower())

palsson, master. gosta leonard
johnson, mrs. oscar w (elisabeth vilhelmina berg)
nasser, mrs. nicholas (adele achem)
sandstrom, miss. marguerite rut
bonnell, miss. elizabeth
saundercock, mr. william henry
andersson, mr. anders johan
vestrom, miss. hulda amanda adolfina


In [ ]:
#function
def uppercase(name):
  return name.upper()

#call
df['Name'].apply(uppercase)[:5]  #apply(function call garney without parenthesis)

0                              BRAUND, MR. OWEN HARRIS
1    CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                               HEIKKINEN, MISS. LAINA
3         FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                             ALLEN, MR. WILLIAM HENRY
Name: Name, dtype: object

In [ ]:
def lowercase(name):
  return name.lower()

df['Name'].apply(lowercase)[:5]

0                              braund, mr. owen harris
1    cumings, mrs. john bradley (florence briggs th...
2                               heikkinen, miss. laina
3         futrelle, mrs. jacques heath (lily may peel)
4                             allen, mr. william henry
Name: Name, dtype: object

In [ ]:
def group(name):
  return name.count()

df.groupby('Sex').apply(group)

/tmp/ipython-input-1224505261.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Sex').apply(group)


PassengerId  Survived  Pclass  Name  Sex  Age  SibSp  Parch  Ticket  \
Sex                                                                           
female          314       314     314   314  314  261    314    314     314   
male            577       577     577   577  577  453    577    577     577   

        Fare  Cabin  Embarked  
Sex                            
female   314     97       312  
male     577    107       577

In [ ]:
#concatenation
a = {
    'id':[1,2,3],
    'first_name':['ram','hari','sita'],
    'last_name':['Shrestha','Pradhan','Malakar']
}
b = {
    'id':[4,5,6],
    'first_name':['shyam','rita','gita'],
    'last_name':['Pokhrel','Thapa','Sharma']
}
a1 = pd.DataFrame(a,columns=['id','first_name','last_name'])
b1 = pd.DataFrame(b,columns=['id','first_name','last_name'])
pd.concat([a1,b1],axis=1)


id first_name last_name  id first_name last_name
0   1        ram  Shrestha   4      shyam   Pokhrel
1   2       hari   Pradhan   5       rita     Thapa
2   3       sita   Malakar   6       gita    Sharma

In [ ]:
#merge
employee_data = {
    'employee_id':[1,2,3,4],
    'name':['ram','hari','sita','gita']
}
sales_data = {
    'employee_id':[3,4,5,6],
    'total_sales':[23456,2565,675,2450]
}
ed1 = pd.DataFrame(employee_data,columns=['employee_id','name'])
sd1 = pd.DataFrame(sales_data,columns=['employee_id','total_sales'])
pd.merge(ed1,sd1,on='employee_id', how = "outer")  #outer - combination of left and right how = left/right/inner/outer

employee_id  name  total_sales
0            1   ram          NaN
1            2  hari          NaN
2            3  sita      23456.0
3            4  gita       2565.0
4            5   NaN        675.0
5            6   NaN       2450.0

<h1> Handling numerical Dataset </h1>


In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
feature = np.array([[-200.6],[-100.3],[0.0],[100.1],[900.9]])

#create scaler
minmax_scaler = MinMaxScaler(feature_range=(0,1))

#transform the feature
scaled_feature = minmax_scaler.fit_transform(feature)
print(scaled_feature)
print(feature)

[[0.        ]
 [0.09105765]
 [0.1821153 ]
 [0.27299138]
 [1.        ]]
[[-200.6]
 [-100.3]
 [   0. ]
 [ 100.1]
 [ 900.9]]


In [ ]:
#StandardScalar
#mean chai 0 and standard deviation chai 1
from sklearn.preprocessing import StandardScaler
feature = np.array([[-200.6],[-100.3],[0.0],[100.1],[900.9]])

standard_scaler = StandardScaler()
scaled_feature = standard_scaler.fit_transform(feature)
print(scaled_feature)

[[-0.86578289]
 [-0.61084183]
 [-0.35590077]
 [-0.10146807]
 [ 1.93399356]]


In [ ]:
print(scaled_feature.mean())
print(scaled_feature.std())

0.0
0.9999999999999999


In [ ]:
#training data lai ekkai choti fit_transform garna milxa
#test data lai chai ekkai choti fit_transform garna mildaina , test data lai transform matra garney

<h1> Imputing Missing values </h1>

In [45]:
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

In [51]:
#make matrix which include features
feature, _ = make_blobs(n_samples = 1000, n_features = 2, random_state = 1) #random_state ma chai value jun diyeko xa tehi nai hunu paryo change hunu vayena
print(feature)

[[-3.05837272  4.48825769]
 [-8.60973869 -3.72714879]
 [ 1.37129721  5.23107449]
 ...
 [-1.91854276  4.59578307]
 [-1.79600465  4.28743568]
 [-6.97684609 -8.89498834]]


In [50]:
scaler = StandardScaler()
scaled_feature = scaler.fit_transform(feature)
print(scaled_feature)

[[ 0.87301861  1.31426523]
 [-0.67073178 -0.22369263]
 [ 2.1048424   1.45332359]
 ...
 [ 1.18998798  1.33439442]
 [ 1.22406396  1.27667052]
 [-0.21664919 -1.19113343]]


In [54]:
# replace the first features first value with missing value
true_value = scaled_feature[0,0]
scaled_feature[0,0] = np.nan
print(scaled_feature)


[[        nan  1.31426523]
 [-0.67073178 -0.22369263]
 [ 2.1048424   1.45332359]
 ...
 [ 1.18998798  1.33439442]
 [ 1.22406396  1.27667052]
 [-0.21664919 -1.19113343]]


In [56]:
KNN_imputer = KNNImputer(n_neighbors = 5)  #data should be highly correlated , it is used in small and medium datasets , it is used where imputting is being done from inside
imputer_value = KNN_imputer.fit_transform(scaled_feature)
print(imputer_value)

[[ 1.09592629  1.31426523]
 [-0.67073178 -0.22369263]
 [ 2.1048424   1.45332359]
 ...
 [ 1.18998798  1.33439442]
 [ 1.22406396  1.27667052]
 [-0.21664919 -1.19113343]]


In [57]:
from sklearn.impute import SimpleImputer  #simpleInputer is used for large datasets and it has high speed and data arenot correlated
Simple_imputer = SimpleImputer()
imputer_value = Simple_imputer.fit_transform(scaled_feature)
print(imputer_value)


[[-8.73892504e-04  1.31426523e+00]
 [-6.70731775e-01 -2.23692628e-01]
 [ 2.10484240e+00  1.45332359e+00]
 ...
 [ 1.18998798e+00  1.33439442e+00]
 [ 1.22406396e+00  1.27667052e+00]
 [-2.16649193e-01 -1.19113343e+00]]


<h1> Converting Nominal Categorical Data into Numerical </h1>


In [58]:
#nominal data
data1 = np.array([
    ['Kathmandu'],['Pokhara'],['Bhaktapur'],['Chitwan']
])

In [63]:
from sklearn.preprocessing import LabelBinarizer
one_hot = LabelBinarizer()
feature_label= one_hot.fit_transform(data1)
print(feature_label)
print(one_hot.classes_)

[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]
['Bhaktapur' 'Chitwan' 'Kathmandu' 'Pokhara']
