<a href="https://colab.research.google.com/github/subupkrl/Python/blob/master/DS_Day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> Stemming Words </h1>

In [1]:
from nltk.stem import PorterStemmer
text = 'i am going to the college for meeting and traditional store.'

#tokenization
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize
wordtokenize = word_tokenize(text)
print(wordtokenize)

#implementing stemmer - short form ma aauxa testo word ko meaning na huna ni sakxa
ps = PorterStemmer()
for word in wordtokenize:
    print(ps.stem(word))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


['i', 'am', 'going', 'to', 'the', 'college', 'for', 'meeting', 'and', 'traditional', 'store', '.']
i
am
go
to
the
colleg
for
meet
and
tradit
store
.


In [2]:
from nltk.stem import WordNetLemmatizer
text = 'i am going to the college for meeting and traditional store.'

#tokenization
import nltk
nltk.download('wordnet')
from nltk.tokenize import word_tokenize
wordtokenize = word_tokenize(text)
print(wordtokenize)

#implementing wordnetlemmatizer
lemmatizer = WordNetLemmatizer()
for word in wordtokenize:
    print(lemmatizer.lemmatize(word,pos='v'))

[nltk_data] Downloading package wordnet to /root/nltk_data...


['i', 'am', 'going', 'to', 'the', 'college', 'for', 'meeting', 'and', 'traditional', 'store', '.']
i
be
go
to
the
college
for
meet
and
traditional
store
.


In [3]:
# pos_tag ko kaam vaneko part of speech k xa vanera herney ho
from nltk import pos_tag
import nltk
nltk.download('averaged_perceptron_tagger_eng')
from nltk.tokenize import word_tokenize
text = 'i am going to the college for meeting'
tokens = word_tokenize(text)
print(pos_tag(tokens))

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...


[('i', 'NN'), ('am', 'VBP'), ('going', 'VBG'), ('to', 'TO'), ('the', 'DT'), ('college', 'NN'), ('for', 'IN'), ('meeting', 'NN')]


[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


In [4]:
#bag of words - kunai pani words kati choti repeat vaako xa vanera diney
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
text = np.array([
    'I am going to the college for meeting and traditional store.',
    'I live in Nepal',
    'I study in Ambikeshwari college',
])
vectorizer = CountVectorizer()
bag_of_words = vectorizer.fit_transform(text)
print(bag_of_words.toarray())
print(vectorizer.vocabulary_)

[[1 0 1 1 1 1 0 0 1 0 1 0 1 1 1]
 [0 0 0 0 0 0 1 1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 1 0 0 0 0 1 0 0 0]]
{'am': 0, 'going': 5, 'to': 13, 'the': 12, 'college': 3, 'for': 4, 'meeting': 8, 'and': 2, 'traditional': 14, 'store': 10, 'live': 7, 'in': 6, 'nepal': 9, 'study': 11, 'ambikeshwari': 1}


In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
nltk.download('punkt_tab')
nltk.download('wordnet')


url = "https://www.naasasecurities.com.np/"
response = requests.get(url)
html_content = response.content
soup = BeautifulSoup(html_content,'lxml')

first_para = soup.find('p')

if first_para:
    print(first_para.text)

    wordtokenize = word_tokenize(first_para.text)
    print(wordtokenize)

    lemmatizer = WordNetLemmatizer()
    for word in wordtokenize:
        print(lemmatizer.lemmatize(word))
else:
    print("No paragraph tag found on the webpage.")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


No paragraph tag found on the webpage.


In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
nltk.download('punkt_tab')
nltk.download('wordnet')


url = "https://edusanjal.com/"
response = requests.get(url)
html_content = response.content
soup = BeautifulSoup(html_content,'lxml')

first_para = soup.find('p')
print(first_para.text)

wordtokenize = word_tokenize(first_para.text)
print(wordtokenize)

lemmatizer = WordNetLemmatizer()
for word in wordtokenize:
    print(lemmatizer.lemmatize(word))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


 Have questions? Ask in our Forum. 
['Have', 'questions', '?', 'Ask', 'in', 'our', 'Forum', '.']
Have
question
?
Ask
in
our
Forum
.


In [7]:
#sentiment analysis
from transformers import pipeline
classifier = pipeline('sentiment-analysis')
s1 = classifier('I hate coding! Its absolutely worst')
s2 = classifier('I love coding! Its absolutely best')
print(s1)
print(s2)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cpu


[{'label': 'NEGATIVE', 'score': 0.9997965693473816}]
[{'label': 'POSITIVE', 'score': 0.999850869178772}]


In [8]:
classifier = pipeline('sentiment-analysis')
texts = ["I love this product",
         "This is the worst experience ever",
         "It's okay, not great but not bad"]
text = classifier(texts)
print(text)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9998788833618164}, {'label': 'NEGATIVE', 'score': 0.9997739195823669}, {'label': 'POSITIVE', 'score': 0.9995349645614624}]


In [11]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import nltk
from nltk.tokenize import sent_tokenize

nltk.download('punkt_tab')

url = 'https://edusanjal.com/'
response = requests.get(url)
html_content = response.content
soup = BeautifulSoup(html_content,'lxml')

first_para = soup.find('p')
print(first_para.text)

sentenize = sent_tokenize(first_para.text)
print(sentenize)

sentence = classifier(sentenize)
print(sentence)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


 Have questions? Ask in our Forum. 
[' Have questions?', 'Ask in our Forum.']
[{'label': 'NEGATIVE', 'score': 0.9822397232055664}, {'label': 'POSITIVE', 'score': 0.9581009745597839}]


<h1> Handling Date & Time </h1>

In [14]:
import numpy as np
import pandas as pd

date_data = np.array([
    '09-12-2025 02:03:40 PM',
    '05-10-2024 11:40:23 PM',
    '10-08-2025 12:01:40 PM'
])
#convert to datetime
[pd.to_datetime(date,format = '%d-%m-%Y %I:%M:%S %p')for date in date_data]

[Timestamp('2025-12-09 14:03:40'),
 Timestamp('2024-10-05 23:40:23'),
 Timestamp('2025-08-10 12:01:40')]

In [31]:
#selecting dates and times
df = pd.DataFrame()
df['Date']=pd.date_range('1/1/2023',periods=150,freq='W')
print(df.head())
print(df.tail())


        Date
0 2023-01-01
1 2023-01-08
2 2023-01-15
3 2023-01-22
4 2023-01-29
          Date
145 2025-10-12
146 2025-10-19
147 2025-10-26
148 2025-11-02
149 2025-11-09


In [32]:
df_date = df[(df['Date'] >= '1/6/2023') & (df['Date'] <= '1/6/2025')]
print(df_date)

          Date
1   2023-01-08
2   2023-01-15
3   2023-01-22
4   2023-01-29
5   2023-02-05
..         ...
101 2024-12-08
102 2024-12-15
103 2024-12-22
104 2024-12-29
105 2025-01-05

[105 rows x 1 columns]


In [33]:
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day
df['hour'] = df['Date'].dt.hour
df['minute'] = df['Date'].dt.minute
df.head()

Date  year  month  day  hour  minute
0 2023-01-01  2023      1    1     0       0
1 2023-01-08  2023      1    8     0       0
2 2023-01-15  2023      1   15     0       0
3 2023-01-22  2023      1   22     0       0
4 2023-01-29  2023      1   29     0       0

In [44]:
Arrived =  pd.to_datetime('12/2/2024')
Departure = pd.to_datetime('12/9/2024')
df_date = Departure - Arrived
print(df_date)

7 days 00:00:00
